### ISSUE TITLE
Specify Python version

### ISSUE THREAD

**Issue by aodj** [sanjeevan/flask-json-schema#1]
Looking at some of the [syntax](https://github.com/sanjeevan/flask-json-schema/blob/master/flask_json_schema/__init__.py#L27) it looks like this is a Python 3 only project. Could you specify this somewhere in the README (or the [`setup.py`](https://github.com/sanjeevan/flask-json-schema/blob/master/setup.py#L22-L25)) so that it's obvious.

**Comment by sanjeevan** [comment]
Thanks for the heads up @aodj I've updated the code so that it'll work with Python 2 and 3
